name: Unity Build Actions

on:
  # Triggers the workflow on push event but only for the "main" branch.
  push: {}

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
  UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
  PROJECT_PATH: .

jobs:
  build:
    name: Build for ${{ matrix.targetPlatform }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - targetPlatform: iOS
            os: macos-latest
          - targetPlatform: Android
            os: ubuntu-latest
          - targetPlatform: WebGL
            os: ubuntu-latest
          - targetPlatform: StandaloneWindows
            os: windows-latest

    runs-on: ${{ matrix.os }}
    steps:
      - run: echo 'The target platform is ${{ matrix.targetPlatform }} on ${{ matrix.os }}'
